### ISSUE TITLE
TypeError: descriptor 'union' for 'set' objects doesn't apply to a 'range' object

### ISSUE THREAD

**Issue by danpaulsmith** [tctianchi/pyvenn#10]
Using the example in the README:

TypeError: descriptor 'union' for 'set' objects doesn't apply to a 'range' object

![Screenshot 2020-02-06 at 14 39 12](https://user-images.githubusercontent.com/582589/73946871-83ddf800-48ee-11ea-9f29-126c08c785ef.png)

**Comment by danpaulsmith** [comment]
Sorry - I was using the forked version on PyPi

**Comment by nomechrif** [comment]
![Capture](https://github.com/tctianchi/pyvenn/assets/130862280/1ec71712-fda2-4a89-a0d9-818aa0cf6a14)
