### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by helmutcarter** [tctianchi/pyvenn#19]
I cloned the repo, `cd`'d in, typed `python3` and hit enter. I tried importing venn, and the following happened:

`>>> import venn`

`Traceback (most recent call last):`

`  File "<stdin>", line 1, in <module>`
 ` File "/my/path/pyvenn/venn.py", line 3, in <module>
    from collections import Iterable`
`ImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)`

**Comment by tctianchi** [comment]
The `Iterable` was removed from `collections` in Python 3.10.
Change that line into
```
from collections.abc import Iterable
```

**Comment by tctianchi** [comment]
fixed.

**Comment by ronixbhaskar** [comment]
> The `Iterable` was removed from `collections` in Python 3.10. Change that line into
> 
> ```
> from collections.abc import Iterable
> ```

Thanks a lot worked out well

**Comment by mial100** [comment]
Pls guys help me out, how can I go about this, pls break down your explanation because I don’t see to understand what you mean in collection??

**Comment by zohansyahfatomi** [comment]
> 

It's worked. But I don't know why XD

**Comment by ronixbhaskar** [comment]
How??

**Comment by pietrovieira** [comment]
Fixed:

![image](https://github.com/tctianchi/pyvenn/assets/299859/b73acfd8-f3da-44a7-a2e2-00a25dba3672)

**Comment by elrive9** [comment]
> Fijado:
> 
> ![image](https://github.com/tctianchi/pyvenn/assets/299859/b73acfd8-f3da-44a7-a2e2-00a25dba3672)

Bt. En que parte es que se debe poner dicha programación?
