### ISSUE TITLE
labels/names not displayed

### ISSUE THREAD

**Issue by robertzeibich** [tctianchi/pyvenn#20]
I am using Python 3.8.3. Do you know why the labels/names are not displayed?

<img width="444" alt="labels_names_venn4" src="https://user-images.githubusercontent.com/73748542/169727941-ba647164-6a7f-40ff-a72f-1d36979d090c.PNG">

**Comment by tctianchi** [comment]
Is draw_text working alone?
```python
from venn import draw_text
import matplotlib.pyplot as plt

fig = plt.figure(0)
ax = fig.add_subplot(111, aspect='equal')
ax.set_axis_off()
ax.set_ylim(bottom=0.0, top=1.0)
ax.set_xlim(left=0.0, right=1.0)
draw_text(fig, ax, 0.13, 0.18, 'A')
```

![image](https://user-images.githubusercontent.com/7827456/169787256-86fa4886-f17c-4607-9302-8cd1baa99099.png)

**Comment by robertzeibich** [comment]
ImportError: cannot import name 'draw_text' from 'venn' (/scratch/xm41/rzei0002/miniconda/lib/python3.8/site-packages/venn/__init__.py)

**Comment by tctianchi** [comment]
Your path (site-packages/venn/init.py) implies that your question might be related to a fork of this repository.
