### ISSUE TITLE
cannot set dpi

### ISSUE THREAD

**Issue by alexwu66666** [tctianchi/pyvenn#21]
Hi there,

I found that we cannot set 'dpi' as optional argument when calling venn() function.

Best regards,
Chao

**Comment by tctianchi** [comment]
I can not reproduce your question.

```
labels = venn.get_labels([range(10), range(5, 15)], fill=['number', 'logic'])
fig, ax = venn.venn2(labels, dpi=300)
fig.savefig('venn2-300.png', bbox_inches='tight')
plt.close()

fig, ax = venn.venn2(labels, dpi=96)
fig.savefig('venn2-96.png', bbox_inches='tight')
plt.close()
```

The code generates 2 different images.

Please append your code.

**Comment by tctianchi** [comment]
There is no "venn()" function in this repository. I believe that your question is related to a fork of this repository.
