### ISSUE TITLE
UserWarning: `venn4()` is retained for backwards compatibility; use `venn()` instead

### ISSUE THREAD

**Issue by NantiaL** [tctianchi/pyvenn#24]
Hey, 

so after using `venn4()` I am getting the following warning message:

`UserWarning: venn4() is retained for backwards compatibility; use venn() instead`

Any ideas why this happens and how to fix it?

**Comment by tctianchi** [comment]
I believe that your question might be related to a fork of this repository rather than mine. ex: I've never publish this code to pip.

Please provide some additional context, like how you install the code.
