### ISSUE TITLE
matplotlib is currently using a non-GUI backend ERROR

### ISSUE THREAD

**Issue by AgustinPardo** [tctianchi/pyvenn#3]
Hello,
I'm trying to run the first code lines of the tutorial:

> import matplotlib
> matplotlib.use('Agg')
> import venn
> labels = venn.get_labels([
>             range(10),
>             range(5, 15)
>         ], fill=['number', 'logic'])
> print labels
> fig, ax = venn.venn2(labels, names=['list 1', 'list 2'])
> fig.show()

And I recibe this error:

> /usr/local/lib/python2.7/dist-packages/matplotlib/figure.py:459: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
>   "matplotlib is currently using a non-GUI backend, "

Do you know what is the problem and how to solve it?

**Comment by osp-ng** [comment]
The error message seems to imply that you are working in a headless console. So fig.show() is meaningless. Are you looking for:

fig.savefig('demo.png', bbox_inches='tight')

**Comment by AgustinPardo** [comment]
That worked out!

**Comment by L7c8ana** [comment]
If UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())

and using 
    import matplotlib
    # Agg backend runs without a display
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

Use fig.savefig('demo.pdf')

**Comment by Hu-Charles** [comment]
it doesnt work

**Comment by rchuso** [comment]
Try this: matplotlib.use( 'tkagg' )

**Comment by ash-aldujaili** [comment]
```
%matplotlib inline
```

**Comment by eavelardev** [comment]
install python-tk or python3-tk for python3

sudo apt install python3-tk

**Comment by LakshyaKhatri** [comment]
Perfect :+1:

**Comment by LakshyaKhatri** [comment]
> install python-tk or python3-tk for python3
> 
> sudo apt install python3-tk

Perfect :+1:

**Comment by ericnjogu** [comment]
> ```
> %matplotlib inline
> ```

Works great with jupyter notebook

**Comment by marwa9** [comment]
import cv2
...
fig.show()
cv2.waitKey(0)

https://www.pyimagesearch.com/2015/08/24/resolved-matplotlib-figures-not-showing-up-or-displaying/

**Comment by san-qi** [comment]
> install python-tk or python3-tk for python3
> 
> sudo apt install python3-tk

nice

**Comment by godabavinay** [comment]
> install python-tk or python3-tk for python3
> 
> sudo apt install python3-tk

Thanks it worked.

**Comment by Mirocle007** [comment]
> Try this: matplotlib.use( 'tkagg' )

Thanks it worked.

**Comment by Villjoie** [comment]
Thanks it worked!

**Comment by gregory-volkov** [comment]
I was using venv with several versions of Python installed in VM. Installing python3-tk did not work.
But installing the PyQt5 via pip solved this problem for me:
```
pip install PyQt5
```

**Comment by neurosignal** [comment]
Just give the command:
`%matplotlib qt5`

if qt5 is not available, install it first as:
`pip install PyQt5`

**Comment by BoyalSuhail** [comment]
Hello sir I want to run this code but I'm unable to run this code sir can you help me from beginning...

**Comment by BoyalSuhail** [comment]
![Uploading IMG20211107184632.jpg…]
this type of errors shows when I copy the code and run in Jupiter notebook

**Comment by neomiraculous** [comment]
> install python-tk or python3-tk for python3
> 
> sudo apt install python3-tk

God bless you!!!
problem solved.
