### ISSUE TITLE
How to show the label name beside the venn,(not the legened)

### ISSUE THREAD

**Issue by IamMr-Cool** [tctianchi/pyvenn#4]
hello,i meet a problem that it can not show label name beside venn using your example code. is there any parameter to set to show the label name beside each set int the venn plot.

**Comment by tctianchi** [comment]
You can test the following code. A line of text should appear on the screen. If not, you can find the reason, maybe the problem is due to the pyplot environment. This code is part of venn.py.

```python
import matplotlib.pyplot as plt

figsize = (9, 7)
dpi = 96
fontsize = 14
text = 'test'
color = [0, 0, 0, 1]
fig = plt.figure(0, figsize=figsize, dpi=dpi)
ax = fig.add_subplot(111, aspect='equal')
ax.set_axis_off()
ax.set_ylim(bottom=0.0, top=0.7)
ax.set_xlim(left=0.0, right=1.0)
ax.text(
    0.5, 0.35, text,
    horizontalalignment='center',
    verticalalignment='center',
    fontsize=fontsize,
    color=color)
plt.show()
```
