### ISSUE TITLE
Error when import ing using Python 2.7

### ISSUE THREAD

**Issue by barbarian1803** [tctianchi/pyvenn#5]
I got this error:

File "/opt/mypython/local/lib/python2.7/site-packages/venn/_venn.py", line 101
def draw_venn(*, petal_labels, dataset_labels, hint_hidden, colors, figsize, fontsize, legend_loc, ax):
                         ^
SyntaxError: invalid syntax

It seems there is a problem in the asterisk sign

**Comment by tctianchi** [comment]
The code you posted is not part of this repository.

There is no "*" syntax in python.
