### ISSUE TITLE
module 'venn' has no attribute 'get_labels'

### ISSUE THREAD

**Issue by vivekruhela** [tctianchi/pyvenn#9]
Hi,

I am trying to work with examples given in `demo.py` but I am getting an error that `module 'venn' has no attribute 'get_labels'`. I am using this package in windows 10 and jupyter notebook with python-3. I have attached  the screenshot for the error I am getting.
![Screenshot (66)](https://user-images.githubusercontent.com/13174913/72200783-9726b080-3473-11ea-8465-f890152ec09c.png)

**Comment by tctianchi** [comment]
Can you run
```
%ls
```

Because I know nothing about your project structure. My expectation of "%ls" is:
```
2020/02/01  01:07                 0 __init__.py
2020/02/01  01:08    <DIR>          __pycache__
2020/02/01  01:07             1,398 demo.py
2020/02/01  01:07             1,210 LICENSE
2020/02/01  01:07             1,958 README.md
2020/02/01  01:12             1,258 Untitled.ipynb
2020/02/01  01:07            21,816 venn.py
```

**Comment by tctianchi** [comment]
I think you may be using a fork version instead of the code in this project, as mentioned in other recent issues.
